core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.legal_notice, name='legals')
]

favorite/urls.py
from django.urls import path

from . import views

app_name = 'favorite'

urlpatterns = [
    path('', views.favorites, name='favorites'),
    path('api/add_favorite/<int:substitute_product_id>', views.add_favorite, name='add_favorite'),
    path('api/remove_favorite/<int:product_id>', views.remove_favorite, name='remove_favorite')
]

openfoodfacts/urls.py
from django.urls import path

from . import views

app_name = 'openfoodfacts'

urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('results/<int:rating_filter>/', views.results, name='results'),
    path('results_with_filter/<str:search_input>/', views.results_with_filter, name='results_with_filter'),
    path('detail/<int:product_id>/', views.product_detail, name='detail'),
    path('api/get_products/', views.get_products, name='get_products'),
]

purbeurre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('openfoodfacts.urls', namespace='openfoodfacts')),
    path('user/', include('user.urls', namespace='user')),
    path('favorites/', include('favorite.urls', namespace='favorite')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('legals/', include('core.urls', namespace='core')),
    path('content/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.authentication, name='authentication'),
    path('logout/', views.view_logout, name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path('account/', views.account, name='account')
]

core/views.py
from django.shortcuts import render


def legal_notice(request):
    return render(request, 'core/legals.html', {'status': False})

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Pur beurre</title>
    {% block top_scripts %}
    <!-- Font Awesome icons-->
    <link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Google Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- JQUERY CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" type="text/css" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap.min.css" type="text/css"
        rel="stylesheet">

    <!-- Plugin CSS -->
    <link href="{% static 'core/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom Template CSS -->
    <link href="{% static 'core/css/creative.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/nav.css' %}" rel="stylesheet">

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    {% block nav %}
        {% include "core/nav.html" %}
    {% endblock nav %}
  
    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; Loïc Tessier</div>
      <div class="small text-center text-muted">
        <a href="{% url 'core:legals' %}">Mentions légales</a>
      </div>
    </div>
  </footer>

    {% block bottom_scripts %}
    <!-- JQUERY Javascript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js" type="text/javascript"></script>

    <!-- Bootstrap Javascript -->
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin Javascript -->
    <script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'core/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom template Javascript -->
    <script src="{% static 'core/js/creative.min.js' %}"></script>

    <script src="{% static '/openfoodfacts/js/autocomplete.js' %}"></script>

    {% endblock %}
</body>

</html>

core/templates/core/legals.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <h1>Mentions légales</h1>
        <div class="col-lg-12 text-white mb-4">
            <p>Le présent site web a été réalisé par <a target="_blank" href="https://www.linkedin.com/in/loictessier/">Loïc Tessier</a> pour la société PurBeurre. Le code source est <a target="_blank" href="https://github.com/loictessier/purbeurre-app">disponible ici</a>.</p>
            <p>Le site utilise les éléments suivants:</p>
            <dl id="legal-notices">
                <dt>L'icône de carotte de la barre de navigation</dt><dd>Créée par <a target="_blank" href="https://thenounproject.com/term/carrot/29691/">Fabien <span class="caps">Jouin</span></a>.</dd>
                <dt>Les images de Remy et Colette</dt><dd>fournies par <a target="_blank" href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/introduction/Notre-identit%C3%A9">OpenClassRooms</a> dans le cadre d'un projet pédagogique.</dd>
                <dt>Les polices de caractères </dt><dd> proviennent de <a target="_blank" href="https://fonts.google.com/">Google Fonts.</a></dd>
                <dt>Le <em>template</em></dt><dd> est adapté de <a target="_blank" href="https://github.com/BlackrockDigital/startbootstrap-creative">Start Bootstrap Creative.</a></dd>
            </dl>
            <p class="">Aucune donnée personnelle n'est exploitée par ce site, hormis les adresses emails des membres inscrits. Actuellement, ces données servent strictement et uniquement au bon fonctionnement du site web. Toute modification de cette clause vous sera communiquée et soumise à votre validation formelle.</p>
        </div>
    </div>
</header>

{% endblock %}

core/templates/core/nav.html
{% load static %}

{% if header %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
{% else %}
<nav class="navbar navbar-expand-lg navbar-light py-3 navbar-scrolled">
{% endif %}
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" id="title" href="{% url 'openfoodfacts:index' %}">
            <img class="fas mr-2" src="{% static 'core/img/portfolio/fullsize/logo.png' %}" width="50" height="50" />
            Pur Beurre
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% include "openfoodfacts/search-nobutton.html" %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:account' %}"><i class="fas fa-user fa-2x"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'favorite:favorites' %}"><i class="fas fa-carrot fa-2x"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:authentication' %}"><i class="fas fa-sign-in-alt fa-2x"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'user:signup' %}"><i class="fas fa-user-plus fa-2x"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>