core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.legal_notice, name='legals')
]

favorite/urls.py
from django.urls import path

from . import views

app_name = 'favorite'

urlpatterns = [
    path('', views.favorites, name='favorites'),
    path('api/add_favorite/<int:substitute_product_id>', views.add_favorite, name='add_favorite'),
    path('api/remove_favorite/<int:product_id>', views.remove_favorite, name='remove_favorite')
]

openfoodfacts/urls.py
from django.urls import path

from . import views

app_name = 'openfoodfacts'

urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('results/<int:rating_filter>/', views.results, name='results'),
    path('results_with_filter/<str:search_input>/', views.results_with_filter, name='results_with_filter'),
    path('detail/<int:product_id>/', views.product_detail, name='detail'),
    path('api/get_products/', views.get_products, name='get_products'),
]

purbeurre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('openfoodfacts.urls', namespace='openfoodfacts')),
    path('user/', include('user.urls', namespace='user')),
    path('favorites/', include('favorite.urls', namespace='favorite')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('legals/', include('core.urls', namespace='core')),
    path('content/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

openfoodfacts/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('Nom', max_length=200, unique=True)
    off_identifier = models.CharField('Identifiant Openfoodfacts', max_length=200)

    class Meta:
        verbose_name = "categorie"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Nom', max_length=200, unique=True)
    nutriscore = models.CharField('Nutriscore', max_length=1)
    img_nutrinfo_url = models.URLField('Image des informations nutritionnelles', max_length=2100, null=True)
    img_url = models.URLField('Image du produit', max_length=2100, null=True)
    off_url = models.URLField('Lien vers la page Openfoodfacts', max_length=2100, null=True)
    popularity = models.IntegerField('Score de popularité', null=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='categorie')

    class Meta:
        verbose_name = "aliment"

    def __str__(self):
        return self.name

openfoodfacts/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.db.models import Avg
from django.db.models.functions import Coalesce

from .models import Product
from user.models import Profile

import json
import re


# Create your views here.
def index(request):
    return render(request, 'openfoodfacts/index.html', {'header': True})


def get_products(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        products = Product.objects.filter(name__icontains=q).order_by('-nutriscore', '-popularity')[:5]
        results = []
        for pr in products:
            product_json = {}
            product_json['label'] = pr.name + ' [' + pr.nutriscore + '] '
            product_json['id'] = pr.id
            results.append(product_json)
        data = json.dumps(results)
    else:
        data = json.dumps('fail')
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def results_with_filter(request, search_input):
    if request.method == "POST":
        rating = request.POST['rating-filter']
        request.method = "GET"
        request.GET = request.GET.copy()
        request.GET['search_input'] = search_input

    return results(request, rating)


def results(request, rating_filter=0):
    if request.method == "GET":
        # search for substitutes
        input = request.GET['search_input']
        # remove [] part
        input = re.sub(r'\[.*$', '', input).strip()
        # search substitute
        search_product = (Product.objects.filter(name__icontains=input)
                          .order_by('nutriscore').values('name', 'category', 'img_url', 'pk')[:1])
        if search_product:
            products = (Product.objects.annotate(avg_rating=Coalesce(Avg('ratingproduct__rating'), 0))
                        .filter(category__id=search_product[0]['category'], avg_rating__gte=rating_filter)
                        .order_by('-avg_rating', 'nutriscore', 'popularity')
                        .values('name', 'nutriscore', 'pk', 'img_url', 'avg_rating')[:12])
            search_product_status = True
            search_product = search_product[0]
        else:
            products = []
            search_product_status = False
            search_product = {'input': input}

    # return results template with substitute liste as results
    return render(request, 'openfoodfacts/results.html',
                  {'status': search_product_status,
                   'search': search_product,
                   'results': products,
                   'rating_filter': rating_filter})


def product_detail(request, product_id):
    try:
        product = Product.objects.annotate(avg_rating=Avg('ratingproduct__rating')).get(pk=product_id)
        if request.user.is_authenticated:
            current_profile = Profile.objects.get(user=request.user)
            rating_product = current_profile.ratingproduct_set.filter(product=product)
            if rating_product:
                product.rating = rating_product[0].rating
            else:
                product.rating = 0
    except Exception:
        raise Http404

    return render(request, 'openfoodfacts/detail.html', {'result': product})

openfoodfacts/templates/openfoodfacts/detail.html
{% extends "core/base.html" %}
{% load static %}
{% load favorite_filter %}

{% block top_scripts%}
    {{ block.super }}
    <link href="{% static 'openfoodfacts/css/results.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section class="page-section bg-dark search-banner" style="background-image:url('{{ result.img_url }}')">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-3 mx-auto">
                    <p class="search_title"> {{ result.name }} </p>
                </div>
            </div>
    </div>
    </section>

    <section class="results-section">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <img src="{{ result.img_nutrinfo_url }}">
                </div>
                <div class="col-lg-6 mx-auto">
                    <img src="{% static 'openfoodfacts/img/nutriscore/detail/'|add:result.nutriscore|add:'.svg' %}">
                    {% if request.user.is_authenticated %}
                        {% include "rating/rating-product.html" %}
                    {% endif %}
                    <p>Note moyenne des utilisateurs: {{ result.avg_rating|default:"Aucune note enregistrée" }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 mx-auto mt-5">
                    <a class="btn btn-primary" href="{{ result.off_url }}" target="_blank">Voir la fiche d'OpenFoodFacts</a>
                    {% if request.user.is_authenticated %}
                        {% if result.pk|check_product_favorite:request.user %}
                            <a class="set_favorite btn btn-primary" href="{% url 'favorite:remove_favorite' product_id=result.pk %}"><i class="fas fa-trash-alt"></i> Retirer des favoris</a>
                        {% else %}
                            <a class="set_favorite btn btn-primary" href="{% url 'favorite:add_favorite' substitute_product_id=result.pk %}"><i class="fas fa-save"></i> Sauvegarder</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block bottom_scripts%}
    {{ block.super }}
    <script src="{% static '/favorite/js/favorite-links.js' %}"></script>
{% endblock %}

openfoodfacts/templates/openfoodfacts/index.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
    <header class="masthead text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>Du gras, oui, mais de qualité !</strong>
                    </h1>
                    <hr>
                </div>
                <div class="col-lg-8 mx-auto">
                    <p class="text-faded mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les
                        jours</p>
                    {% include "openfoodfacts/search.html" %}    
                </div>
            </div>
        </div>
    </header>

    <!-- SECTION 2 : PRESENTATION HISTOIRE ET PERSONNAS -->
    <section class="page-section bg-primary" id="about">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">Colette et Remy</h2>
                    <hr class="divider light my-4">
                    <p class="text-white-50 mb-4">Colette Tatou : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
                    <p class="text-white-50 mb-4">Remy : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
                    <div></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <img src="{% static 'openfoodfacts/img/colette.png' %}" height="300" width="150">
                    <div class="text-white-50 mb-4">Colette</div>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <img src="{% static 'openfoodfacts/img/remy.png' %}" height="300" width="225">
                    <div class="text-white-50 mb-4">Remy</div>
                </div>
            </div>
        </div>
    </section>

    <!-- SECTION 3 : CONTACTEZ-NOUS -->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contactez-nous</h2>
                <hr class="divider my-4">
                <p class="text-muted mb-5">Vous avez des questions à nous poser ? Des suggestions pour améliorer le site ? Appelez-nous ou envoyez-nous un mail et nous vous répondrons aussi vite que possible !</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                    <div>+33 0123456789</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                    <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                    <!-- Make sure to change the email address in anchor text AND the link below! -->
                    <p class="d-block">mail@mail.com</a>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

openfoodfacts/templates/openfoodfacts/results.html
{% extends "core/base.html" %}
{% load static %}
{% load favorite_filter %}

{% block top_scripts%}
    {{ block.super }}
    <link href="{% static 'openfoodfacts/css/results.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if status %}
    <section class="page-section bg-dark search-banner" style="background-image:url('{{ search.img_url }}')">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-3 mx-auto">
                    <p class="search_title"> {{ search.name }} </p>
                </div>
            </div>
    </div>
    </section>

    <section class="results-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% include "rating/rating-product-filter.html" %}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="mb-4"> Vous pouvez remplacer cet aliment par : </h2>
                </div>
            </div>
            <div class="row mt-5">
                {% for product in results %}
                <div class="col-lg-4 mb-4 product">
                    <a href="{% url 'openfoodfacts:detail' product_id=product.pk %}">
                        <div class="product-container">
                            <img src="{{ product.img_url }}" height="200" width="150">
                            <img class="top-right" src="{% static 'openfoodfacts/img/nutriscore/result/'|add:product.nutriscore|add:'.png' %}">
                        </div>
                        <div id='product_name'>{{ product.name|add:" ["|add:product.nutriscore|upper|add:"]" }}</div>
                    </a>
                    <div>Note moyenne des utilisateurs: {{ product.avg_rating|default:"Aucune note enregistrée" }}</div>
                    {% if request.user.is_authenticated %}
                        {% if product.pk|check_product_favorite:request.user %}
                            <a class="set_favorite" href="{% url 'favorite:remove_favorite' product_id=product.pk %}"><i class="fas fa-trash-alt"></i> Retirer des favoris</a>
                        {% else %}
                            <a class="set_favorite" href="{% url 'favorite:add_favorite' substitute_product_id=product.pk %}"><i class="fas fa-save"></i> Sauvegarder</a>
                        {% endif %}
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% else %}
    <section class="results-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Aucun produit correspondant à '{{ search.input }}' n'a été trouvé</p>
                </div>
            </div>
        </div>
    </section>
{% endif %}

{% endblock %}

{% block bottom_scripts%}
    {{ block.super }}
    <script src="{% static '/favorite/js/favorite-links.js' %}"></script>
{% endblock %}

openfoodfacts/templates/openfoodfacts/search-nobutton.html
<form method="get" action="{% url 'openfoodfacts:results' %}">
    <input class="search_input" name="search_input" type="text" placeholder="Rechercher">
</form>

openfoodfacts/templates/openfoodfacts/search.html
<form method="get" action="{% url 'openfoodfacts:results' %}">
    <input class="search_input" id="index_search_input" name="search_input" type="text" placeholder="ex: Nutella, coca-cola,...">
    <input class="btn btn-primary" type="submit" value="Rechercher">
</form>