core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.legal_notice, name='legals')
]

openfoodfacts/urls.py
from django.urls import path

from . import views

app_name = 'openfoodfacts'

urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('results/<int:rating_filter>/', views.results, name='results'),
    path('results_with_filter/<str:search_input>/', views.results_with_filter, name='results_with_filter'),
    path('detail/<int:product_id>/', views.product_detail, name='detail'),
    path('api/get_products/', views.get_products, name='get_products'),
]

purbeurre/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('openfoodfacts.urls', namespace='openfoodfacts')),
    path('user/', include('user.urls', namespace='user')),
    path('favorites/', include('favorite.urls', namespace='favorite')),
    path('rating/', include('rating.urls', namespace='rating')),
    path('legals/', include('core.urls', namespace='core')),
    path('content/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rating/urls.py
from django.urls import path

from . import views

app_name = 'rating'

urlpatterns = [
    path('post_rating_product/<int:product_id>', views.post_rating_product, name='post_rating_product'),
    path('api/add_rating_product/<int:product_id>/<int:rating>', views.add_rating_product, name='add_rating_product'),
    path('api/remove_rating_product/<int:product_id>', views.remove_rating_product, name='remove_rating_product'),
]

rating/models.py
from django.db import models

from user.models import Profile
from openfoodfacts.models import Product


# Create your models here.
class RatingProduct(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField('Note', null=False)

    class Meta:
        verbose_name = "note"

    def __str__(self):
        return str(self.rating)

rating/views.py
from django.shortcuts import redirect
from django.http import JsonResponse

from user.models import Profile
from rating.models import RatingProduct
from openfoodfacts.models import Product


# Create your views here.
def post_rating_product(request, product_id):
    if request.method == 'POST':
        rating = request.POST['rating-product']
        if rating != "0":
            add_rating_product(request, product_id, rating)
        else:
            remove_rating_product(request, product_id)

    return redirect('openfoodfacts:detail', product_id=product_id)


def add_rating_product(request, product_id, rating):
    if request.user.is_authenticated:
        current_profile = Profile.objects.get(user=request.user)

        try:
            product = Product.objects.get(id=product_id)
            rating, created = RatingProduct.objects.update_or_create(
                profile=current_profile,
                product=product,
                defaults={'rating': rating})
            status = 200
            res = "La note a été créée / mise à jour"
        except Exception:
            status = 500
            res = "Erreur lors de la création / mise à jour de la note"
    else:
        status = 401
        res = "Erreur d'authentification"

    return JsonResponse({'status': status, 'message': res})


def remove_rating_product(request, product_id):
    if request.user.is_authenticated:
        current_profile = Profile.objects.get(user=request.user)
        try:
            rated_product = Product.objects.get(id=product_id)
            rating_product = current_profile.ratingproduct_set.filter(product=rated_product)
            rating_product.delete()
            status = 200
            res = "La note a été supprimée"
        except Exception:
            status = 500
            res = "Erreur lors de la suppression de la note"
    else:
        status = 401
        res = "Erreur d'authentification"

    return JsonResponse({'status': status, 'message': res})

rating/templates/rating/rating-product-filter.html
<div class="container my-auto">
    <form action="{% url 'openfoodfacts:results_with_filter' search_input=search.name %}" method="POST">
        {% csrf_token %}
        <label for="rating-filter">Filtrer les produits :</label>
        <select name="rating-filter" id="rating-filter">
            <option value="0" {% if '0' == rating_filter %}selected="selected"{% endif %}>Tous</option>
            <option value="1" {% if '1' == rating_filter %}selected="selected"{% endif %}>Note moyenne >= 1</option>
            <option value="2" {% if '2' == rating_filter %}selected="selected"{% endif %}>Note moyenne >= 2</option>
            <option value="3" {% if '3' == rating_filter %}selected="selected"{% endif %}>Note moyenne >= 3</option>
            <option value="4" {% if '4' == rating_filter %}selected="selected"{% endif %}>Note moyenne >= 4</option>
            <option value="5" {% if '5' == rating_filter %}selected="selected"{% endif %}>Note moyenne >= 5</option>
        </select>
        <button type="submit" class="btn btn-secondary" href="">Appliquer le filtre</button>
    </form>
</div>

rating/templates/rating/rating-product.html
<div class="container my-auto">
    <form action="{% url 'rating:post_rating_product' product_id=result.pk %}" method="POST">
        {% csrf_token %}
        <label for="rating-product">Votre note:</label>
        <select name="rating-product" id="rating-product">
            <option value="0" {% if 0 == result.rating %}selected="selected"{% endif %}>Pas de note</option>
            <option value="1" {% if 1 == result.rating %}selected="selected"{% endif %}>1</option>
            <option value="2" {% if 2 == result.rating %}selected="selected"{% endif %}>2</option>
            <option value="3" {% if 3 == result.rating %}selected="selected"{% endif %}>3</option>
            <option value="4" {% if 4 == result.rating %}selected="selected"{% endif %}>4</option>
            <option value="5" {% if 5 == result.rating %}selected="selected"{% endif %}>5</option>
        </select>
        <button id="rating-save-button" type="submit" class="btn btn-secondary" href="">Enregistrer</button>
    </form>
</div>